package io.github.ariellaub.protobus.codegen;

import com.google.protobuf.Descriptors.FileDescriptor;
import com.google.protobuf.Descriptors.MethodDescriptor;
import com.google.protobuf.Descriptors.ServiceDescriptor;
import java.util.ArrayList;
import java.util.List;

/**
 * Writes the protobus classes for one schema: per service, a
 * {@code <Service>Protobus} holding the service's name, an abstract {@code Base}
 * to implement and a typed {@code Proxy} to call it with.
 */
final class Generator {
    private Generator() {}

    record Output(String path, String content) {}

    private static final String RT = "io.github.ariellaub.protobus.";

    static List<Output> generate(FileDescriptor file) {
        List<Output> out = new ArrayList<>();
        for (ServiceDescriptor s : file.getServices()) {
            String pkg = Names.javaPackage(file);
            String cls = s.getName() + "Protobus";
            String path = (pkg.isEmpty() ? "" : pkg.replace('.', '/') + "/") + cls + ".java";
            out.add(new Output(path, service(file, s, pkg, cls)));
        }
        return out;
    }

    /**
     * The Java names of a service's methods, allocated together so none collide:
     * an rpc's own name (escaped when it is a keyword or a base-class member) and,
     * for a unary rpc, its {@code Async} variant. A name already taken, by
     * another rpc or another variant, gets underscores until it is free, so
     * {@code fetch} and {@code fetchAsync} side by side give {@code fetchAsync_}
     * for the first one's async variant.
     */
    record MethodNames(java.util.Map<String, String> plain, java.util.Map<String, String> async) {
        static MethodNames allocate(ServiceDescriptor s) {
            java.util.Set<String> taken = new java.util.HashSet<>(Names.RESERVED_MEMBERS);
            java.util.Map<String, String> plain = new java.util.LinkedHashMap<>();
            java.util.Map<String, String> async = new java.util.LinkedHashMap<>();
            // The rpcs' own names first: they are what callers look for.
            for (MethodDescriptor m : s.getMethods()) {
                if (m.isClientStreaming()) continue;
                plain.put(m.getName(), claim(taken, Names.methodIdentifier(m.getName())));
            }
            for (MethodDescriptor m : s.getMethods()) {
                if (m.isClientStreaming() || m.isServerStreaming()) continue;
                async.put(m.getName(), claim(taken, plain.get(m.getName()) + "Async"));
            }
            return new MethodNames(plain, async);
        }

        private static String claim(java.util.Set<String> taken, String name) {
            String n = name;
            while (taken.contains(n) || Names.JAVA_KEYWORDS.contains(n)) n += "_";
            taken.add(n);
            return n;
        }
    }

    private static String service(FileDescriptor file, ServiceDescriptor s, String pkg, String cls) {
        StringBuilder b = new StringBuilder();
        String holder = Names.descriptorHolder(file);
        b.append("// Generated by protobus-codegen from ").append(file.getName()).append(". Do not edit.\n");
        if (!pkg.isEmpty()) b.append("package ").append(pkg).append(";\n");
        b.append("\n");
        b.append("/**\n * protobus bindings for {@code ").append(s.getFullName()).append("}.\n *\n");
        b.append(" * <p>Implement the service by extending {@link Base}; call it with {@link Proxy}.\n */\n");
        b.append("@javax.annotation.processing.Generated(\"protobus-codegen\")\n");
        b.append("public final class ").append(cls).append(" {\n");
        b.append("    private ").append(cls).append("() {}\n\n");
        b.append("    /** The service's name on the bus, and its contract. */\n");
        b.append("    public static final String SERVICE_NAME = \"").append(s.getFullName()).append("\";\n\n");
        b.append("    /** The schema declaring the service. */\n");
        b.append("    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {\n");
        b.append("        return ").append(holder).append(".getDescriptor();\n");
        b.append("    }\n\n");
        MethodNames names = MethodNames.allocate(s);
        base(b, s, names);
        b.append("\n");
        proxy(b, s, names);
        b.append("}\n");
        return b.toString();
    }

    private static String signature(MethodDescriptor m) {
        return "rpc " + m.getName() + "(" + (m.isClientStreaming() ? "stream " : "")
                + m.getInputType().getFullName() + ") returns (" + (m.isServerStreaming() ? "stream " : "")
                + m.getOutputType().getFullName() + ")";
    }

    private static void base(StringBuilder b, ServiceDescriptor s, MethodNames names) {
        b.append("    /**\n");
        b.append("     * Implements {@code ").append(s.getFullName()).append("}: override its rpcs. An rpc left\n");
        b.append("     * unimplemented answers PROTOCOL_ERROR. Throw a {@link ").append(RT)
                .append("HandledError} to answer the caller\n");
        b.append("     * with an error; anything else thrown is retried.\n     */\n");
        b.append("    public abstract static class Base extends ").append(RT).append("RunnableService {\n");
        b.append("        protected Base(").append(RT).append("Context context) {\n");
        b.append("            this(context, ").append(RT).append("MessageServiceOptions.DEFAULT);\n");
        b.append("        }\n\n");
        b.append("        protected Base(").append(RT).append("Context context, ").append(RT)
                .append("MessageServiceOptions options) {\n");
        b.append("            super(context, options);\n");
        for (MethodDescriptor m : s.getMethods()) {
            if (m.isClientStreaming()) continue;
            String req = Names.messageClass(m.getInputType());
            String id = names.plain().get(m.getName());
            b.append("            register").append(m.isServerStreaming() ? "Stream" : "Unary").append("(\"")
                    .append(m.getName()).append("\", ").append(req).append(".getDefaultInstance(), this::")
                    .append(id).append(");\n");
        }
        b.append("        }\n\n");
        b.append("        @Override\n        public String serviceName() {\n            return SERVICE_NAME;\n        }\n\n");
        b.append("        @Override\n        protected com.google.protobuf.Descriptors.FileDescriptor schema() {\n");
        b.append("            return getDescriptor();\n        }\n");
        for (MethodDescriptor m : s.getMethods()) {
            b.append("\n        /** {@code ").append(signature(m)).append("} */\n");
            if (m.isClientStreaming()) {
                b.append("        // Client streaming is not part of the protobus protocol; this rpc is not served.\n");
                continue;
            }
            String req = Names.messageClass(m.getInputType());
            String res = Names.messageClass(m.getOutputType());
            String id = names.plain().get(m.getName());
            if (m.isServerStreaming()) {
                b.append("        public void ").append(id).append("(").append(req).append(" request, ").append(RT)
                        .append("StreamWriter<").append(res).append("> out, ").append(RT)
                        .append("CallContext context) throws Exception {\n");
            } else {
                b.append("        public ").append(res).append(" ").append(id).append("(").append(req)
                        .append(" request, ").append(RT).append("CallContext context) throws Exception {\n");
            }
            b.append("            throw new ").append(RT).append("InvalidMethodError(\"invalid service method ")
                    .append(m.getName()).append("\");\n        }\n");
        }
        b.append("    }\n");
    }

    private static void proxy(StringBuilder b, ServiceDescriptor s, MethodNames names) {
        b.append("    /**\n");
        b.append("     * Calls {@code ").append(s.getFullName()).append("}. Construct it with an instance name to\n");
        b.append("     * address a service registered under one; {@link #init()} before calling.\n     */\n");
        b.append("    public static class Proxy extends ").append(RT).append("ServiceProxy {\n");
        b.append("        public Proxy(").append(RT).append("Context context) {\n");
        b.append("            this(context, SERVICE_NAME);\n        }\n\n");
        b.append("        public Proxy(").append(RT).append("Context context, String serviceName) {\n");
        b.append("            super(context, serviceName);\n");
        b.append("            context.factory().register(getDescriptor());\n        }\n");
        for (MethodDescriptor m : s.getMethods()) {
            if (m.isClientStreaming()) continue;
            String req = Names.messageClass(m.getInputType());
            String res = Names.messageClass(m.getOutputType());
            String id = names.plain().get(m.getName());
            String name = m.getName();
            b.append("\n        /** {@code ").append(signature(m)).append("} */\n");
            if (m.isServerStreaming()) {
                b.append("        public ").append(RT).append("ProtobusStream<").append(res).append("> ").append(id)
                        .append("(").append(req).append(" request) {\n");
                b.append("            return ").append(id).append("(request, ").append(RT)
                        .append("StreamOptions.DEFAULT);\n        }\n\n");
                b.append("        public ").append(RT).append("ProtobusStream<").append(res).append("> ").append(id)
                        .append("(").append(req).append(" request, ").append(RT).append("StreamOptions options) {\n");
                b.append("            return callStreamTyped(\"").append(name).append("\", request, options,\n");
                b.append("                    parserDecoder(SERVICE_NAME + \".").append(name).append("\", ").append(res)
                        .append(".parser()));\n        }\n");
            } else {
                b.append("        public ").append(res).append(" ").append(id).append("(").append(req)
                        .append(" request) {\n");
                String async = names.async().get(name);
                b.append("            return await(").append(async).append("(request, ").append(RT)
                        .append("CallOptions.DEFAULT));\n        }\n\n");
                b.append("        public ").append(res).append(" ").append(id).append("(").append(req)
                        .append(" request, ").append(RT).append("CallOptions options) {\n");
                b.append("            return await(").append(async).append("(request, options));\n        }\n\n");
                b.append("        public java.util.concurrent.CompletableFuture<").append(res).append("> ").append(async)
                        .append("(").append(req).append(" request) {\n");
                b.append("            return ").append(async).append("(request, ").append(RT)
                        .append("CallOptions.DEFAULT);\n        }\n\n");
                b.append("        public java.util.concurrent.CompletableFuture<").append(res).append("> ").append(async)
                        .append("(").append(req).append(" request, ").append(RT).append("CallOptions options) {\n");
                b.append("            return callTypedAsync(\"").append(name).append("\", request, options,\n");
                b.append("                    parserDecoder(SERVICE_NAME + \".").append(name).append("\", ").append(res)
                        .append(".parser()),\n");
                b.append("                    ").append(res).append("::getDefaultInstance);\n        }\n");
            }
        }
        b.append("    }\n");
    }
}
